table AMZN
	lineageTag: 2fdac968-7097-4790-81ca-38c5f19c10eb

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4227214d-b701-4ba7-87f2-1fb3e63e27ec
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 67f393ac-a28b-4f14-8eb4-c15d3d7d9cfd
			defaultHierarchy: LocalDateTable_a99828b9-e60a-40bf-b5ef-41a27ad9ecbd.'Date Hierarchy'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 8f0bb49b-f7eb-41c3-833b-26a2deaaee0b
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 8409e7d7-301e-49b8-81fe-29973bcff7b0
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: c9f004b2-b57b-4331-9038-28378e4324ea
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: daf16034-48c4-4c71-8cb9-3ae384106edb
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: a829fafc-d3b4-4481-8cb1-dc79c5a41092
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 565e504e-7bff-4b64-8b1c-c0e73a400bd4
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\skart\OneDrive\文档\PowerBI Projects -GIT\PowerBI-training\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

